# Site settings
author: Joseph Cohen
title: Flatiron Blog page
header-img: img/home-bg.png
email: jojocohen57@gmail.com
copyright_name: Joseph Cohen
description: > # this means to ignore newlines until "baseurl:"
  Blogs
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  JOCOghub

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
